name: Frontend
run-name: Builds a frontend APK
on: [push]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install EAS CLI
        run: npm install -g eas-cli@5.9.1
      - name: Install dependencies
        run: npx expo install
      - name: EAS Build
        run: eas build --platform android --profile preview --local
