name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        working-directory: frontend
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
        working-directory: frontend
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
        working-directory: frontend
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: Build on EAS
        run: eas build --platform all --non-interactive
        working-directory: frontend
